apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulumi-go-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zdk/pulumi-gitops
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
